language: c

before_install:
    - sudo apt-add-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes valac libglib2.0-dev libgee-0.8-dev  libjson-glib-dev

script:
    - valac --pkg json-glib-1.0 --pkg gio-2.0 --pkg gee-0.8 src/FFconvert.vala src/FFprobe.vala src/FFmpeg.vala src/exceptions/CodecNotEnabledException.vala src/exceptions/FileOrDirectoryNotFoundException.vala src/exceptions/NullReferenceException.vala src/utils/StringUtil.vala test/FFmpegTest.vala src/exceptions/IllegalArgumentException.vala src/exceptions/IOException.vala src/probe/FFprobeError.vala src/probe/FFprobeFormat.vala src/probe/FFprobeStream.vala -o ffmpeg-cli-wrapper

after_success:
    - bash <(curl -s https://codecov.io/bash)
