language: c

before_install:
    - sudo apt-add-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes valac libglib2.0-dev

script:
    - valac --debug --pkg io-2.0 src/FFconvert.vala src/FFmpeg.vala src/FFcommon.vala src/exceptions/CodecNotEnabledException.vala src/exceptions/FileOrDirectoryNotFoundException.vala src/exceptions/NullReferenceException.vala src/utils/StringUtil.vala test/FFmpegTest.vala src/exceptions/IllegalArgumentException.vala src/exceptions/IOException.vala -o ffmpeg-cli-wrapper
    - ./ffmpeg-cli-wrapper

after_success:
    - bash <(curl -s https://codecov.io/bash)
